# Autogenerated wrapper script for GstPluginsBase_jll for aarch64-apple-darwin
export gstdevicemonitor, gstdiscoverer, gstplay, libgstadder, libgstapp, libgstaudioconvert, libgstaudiomixer, libgstaudiorate, libgstaudioresample, libgstaudiotestsrc, libgstcompositor, libgstencoding, libgstgio, libgstopus, libgstoverlaycomposition, libgstpbtypes, libgstplayback, libgstrawparse, libgstsubparse, libgsttcp, libgsttypefindfunctions, libgstvideoconvert, libgstvideorate, libgstvideoscale, libgstvideotestsrc, libgstvolume

using GStreamer_jll
using Opus_jll
JLLWrappers.@generate_wrapper_header("GstPluginsBase")
JLLWrappers.@declare_library_product(libgstadder, "@rpath/libgstadder.dylib")
JLLWrappers.@declare_library_product(libgstapp, "@rpath/libgstapp.dylib")
JLLWrappers.@declare_library_product(libgstaudioconvert, "@rpath/libgstaudioconvert.dylib")
JLLWrappers.@declare_library_product(libgstaudiomixer, "@rpath/libgstaudiomixer.dylib")
JLLWrappers.@declare_library_product(libgstaudiorate, "@rpath/libgstaudiorate.dylib")
JLLWrappers.@declare_library_product(libgstaudioresample, "@rpath/libgstaudioresample.dylib")
JLLWrappers.@declare_library_product(libgstaudiotestsrc, "@rpath/libgstaudiotestsrc.dylib")
JLLWrappers.@declare_library_product(libgstcompositor, "@rpath/libgstcompositor.dylib")
JLLWrappers.@declare_library_product(libgstencoding, "@rpath/libgstencoding.dylib")
JLLWrappers.@declare_library_product(libgstgio, "@rpath/libgstgio.dylib")
JLLWrappers.@declare_library_product(libgstopus, "@rpath/libgstopus.dylib")
JLLWrappers.@declare_library_product(libgstoverlaycomposition, "@rpath/libgstoverlaycomposition.dylib")
JLLWrappers.@declare_library_product(libgstpbtypes, "@rpath/libgstpbtypes.dylib")
JLLWrappers.@declare_library_product(libgstplayback, "@rpath/libgstplayback.dylib")
JLLWrappers.@declare_library_product(libgstrawparse, "@rpath/libgstrawparse.dylib")
JLLWrappers.@declare_library_product(libgstsubparse, "@rpath/libgstsubparse.dylib")
JLLWrappers.@declare_library_product(libgsttcp, "@rpath/libgsttcp.dylib")
JLLWrappers.@declare_library_product(libgsttypefindfunctions, "@rpath/libgsttypefindfunctions.dylib")
JLLWrappers.@declare_library_product(libgstvideoconvert, "@rpath/libgstvideoconvert.dylib")
JLLWrappers.@declare_library_product(libgstvideorate, "@rpath/libgstvideorate.dylib")
JLLWrappers.@declare_library_product(libgstvideoscale, "@rpath/libgstvideoscale.dylib")
JLLWrappers.@declare_library_product(libgstvideotestsrc, "@rpath/libgstvideotestsrc.dylib")
JLLWrappers.@declare_library_product(libgstvolume, "@rpath/libgstvolume.dylib")
JLLWrappers.@declare_executable_product(gstdevicemonitor)
JLLWrappers.@declare_executable_product(gstdiscoverer)
JLLWrappers.@declare_executable_product(gstplay)
function __init__()
    JLLWrappers.@generate_init_header(GStreamer_jll, Opus_jll)
    JLLWrappers.@init_library_product(
        libgstadder,
        "lib/gstreamer-1.0/libgstadder.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgstapp,
        "lib/gstreamer-1.0/libgstapp.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgstaudioconvert,
        "lib/gstreamer-1.0/libgstaudioconvert.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgstaudiomixer,
        "lib/gstreamer-1.0/libgstaudiomixer.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgstaudiorate,
        "lib/gstreamer-1.0/libgstaudiorate.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgstaudioresample,
        "lib/gstreamer-1.0/libgstaudioresample.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgstaudiotestsrc,
        "lib/gstreamer-1.0/libgstaudiotestsrc.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgstcompositor,
        "lib/gstreamer-1.0/libgstcompositor.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgstencoding,
        "lib/gstreamer-1.0/libgstencoding.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgstgio,
        "lib/gstreamer-1.0/libgstgio.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgstopus,
        "lib/gstreamer-1.0/libgstopus.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgstoverlaycomposition,
        "lib/gstreamer-1.0/libgstoverlaycomposition.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgstpbtypes,
        "lib/gstreamer-1.0/libgstpbtypes.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgstplayback,
        "lib/gstreamer-1.0/libgstplayback.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgstrawparse,
        "lib/gstreamer-1.0/libgstrawparse.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgstsubparse,
        "lib/gstreamer-1.0/libgstsubparse.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgsttcp,
        "lib/gstreamer-1.0/libgsttcp.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgsttypefindfunctions,
        "lib/gstreamer-1.0/libgsttypefindfunctions.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgstvideoconvert,
        "lib/gstreamer-1.0/libgstvideoconvert.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgstvideorate,
        "lib/gstreamer-1.0/libgstvideorate.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgstvideoscale,
        "lib/gstreamer-1.0/libgstvideoscale.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgstvideotestsrc,
        "lib/gstreamer-1.0/libgstvideotestsrc.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgstvolume,
        "lib/gstreamer-1.0/libgstvolume.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        gstdevicemonitor,
        "bin/gst-device-monitor-1.0",
    )

    JLLWrappers.@init_executable_product(
        gstdiscoverer,
        "bin/gst-discoverer-1.0",
    )

    JLLWrappers.@init_executable_product(
        gstplay,
        "bin/gst-play-1.0",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
