# Autogenerated wrapper script for GstPluginsBase_jll for x86_64-w64-mingw32
export gstdevicemonitor, gstdiscoverer, gstplay, libgstadder, libgstapp, libgstaudioconvert, libgstaudiomixer, libgstaudiorate, libgstaudioresample, libgstaudiotestsrc, libgstcompositor, libgstencoding, libgstgio, libgstopus, libgstoverlaycomposition, libgstpbtypes, libgstplayback, libgstrawparse, libgstsubparse, libgsttcp, libgsttypefindfunctions, libgstvideoconvert, libgstvideorate, libgstvideoscale, libgstvideotestsrc, libgstvolume

using GStreamer_jll
using Opus_jll
JLLWrappers.@generate_wrapper_header("GstPluginsBase")
JLLWrappers.@declare_library_product(libgstadder, "libgstadder.dll")
JLLWrappers.@declare_library_product(libgstapp, "libgstapp.dll")
JLLWrappers.@declare_library_product(libgstaudioconvert, "libgstaudioconvert.dll")
JLLWrappers.@declare_library_product(libgstaudiomixer, "libgstaudiomixer.dll")
JLLWrappers.@declare_library_product(libgstaudiorate, "libgstaudiorate.dll")
JLLWrappers.@declare_library_product(libgstaudioresample, "libgstaudioresample.dll")
JLLWrappers.@declare_library_product(libgstaudiotestsrc, "libgstaudiotestsrc.dll")
JLLWrappers.@declare_library_product(libgstcompositor, "libgstcompositor.dll")
JLLWrappers.@declare_library_product(libgstencoding, "libgstencoding.dll")
JLLWrappers.@declare_library_product(libgstgio, "libgstgio.dll")
JLLWrappers.@declare_library_product(libgstopus, "libgstopus.dll")
JLLWrappers.@declare_library_product(libgstoverlaycomposition, "libgstoverlaycomposition.dll")
JLLWrappers.@declare_library_product(libgstpbtypes, "libgstpbtypes.dll")
JLLWrappers.@declare_library_product(libgstplayback, "libgstplayback.dll")
JLLWrappers.@declare_library_product(libgstrawparse, "libgstrawparse.dll")
JLLWrappers.@declare_library_product(libgstsubparse, "libgstsubparse.dll")
JLLWrappers.@declare_library_product(libgsttcp, "libgsttcp.dll")
JLLWrappers.@declare_library_product(libgsttypefindfunctions, "libgsttypefindfunctions.dll")
JLLWrappers.@declare_library_product(libgstvideoconvert, "libgstvideoconvert.dll")
JLLWrappers.@declare_library_product(libgstvideorate, "libgstvideorate.dll")
JLLWrappers.@declare_library_product(libgstvideoscale, "libgstvideoscale.dll")
JLLWrappers.@declare_library_product(libgstvideotestsrc, "libgstvideotestsrc.dll")
JLLWrappers.@declare_library_product(libgstvolume, "libgstvolume.dll")
JLLWrappers.@declare_executable_product(gstdevicemonitor)
JLLWrappers.@declare_executable_product(gstdiscoverer)
JLLWrappers.@declare_executable_product(gstplay)
function __init__()
    JLLWrappers.@generate_init_header(GStreamer_jll, Opus_jll)
    JLLWrappers.@init_library_product(
        libgstadder,
        "lib\\gstreamer-1.0\\libgstadder.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgstapp,
        "lib\\gstreamer-1.0\\libgstapp.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgstaudioconvert,
        "lib\\gstreamer-1.0\\libgstaudioconvert.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgstaudiomixer,
        "lib\\gstreamer-1.0\\libgstaudiomixer.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgstaudiorate,
        "lib\\gstreamer-1.0\\libgstaudiorate.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgstaudioresample,
        "lib\\gstreamer-1.0\\libgstaudioresample.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgstaudiotestsrc,
        "lib\\gstreamer-1.0\\libgstaudiotestsrc.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgstcompositor,
        "lib\\gstreamer-1.0\\libgstcompositor.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgstencoding,
        "lib\\gstreamer-1.0\\libgstencoding.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgstgio,
        "lib\\gstreamer-1.0\\libgstgio.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgstopus,
        "lib\\gstreamer-1.0\\libgstopus.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgstoverlaycomposition,
        "lib\\gstreamer-1.0\\libgstoverlaycomposition.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgstpbtypes,
        "lib\\gstreamer-1.0\\libgstpbtypes.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgstplayback,
        "lib\\gstreamer-1.0\\libgstplayback.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgstrawparse,
        "lib\\gstreamer-1.0\\libgstrawparse.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgstsubparse,
        "lib\\gstreamer-1.0\\libgstsubparse.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgsttcp,
        "lib\\gstreamer-1.0\\libgsttcp.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgsttypefindfunctions,
        "lib\\gstreamer-1.0\\libgsttypefindfunctions.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgstvideoconvert,
        "lib\\gstreamer-1.0\\libgstvideoconvert.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgstvideorate,
        "lib\\gstreamer-1.0\\libgstvideorate.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgstvideoscale,
        "lib\\gstreamer-1.0\\libgstvideoscale.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgstvideotestsrc,
        "lib\\gstreamer-1.0\\libgstvideotestsrc.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgstvolume,
        "lib\\gstreamer-1.0\\libgstvolume.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        gstdevicemonitor,
        "bin\\gst-device-monitor-1.0.exe",
    )

    JLLWrappers.@init_executable_product(
        gstdiscoverer,
        "bin\\gst-discoverer-1.0.exe",
    )

    JLLWrappers.@init_executable_product(
        gstplay,
        "bin\\gst-play-1.0.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
